### ISSUE TITLE
where are the data files?

### ISSUE THREAD

**Issue by theworldisnotflat** [sangonzal/repository-traffic-action#15]
dear @sangonzal your action looks simple and easy and well explained, great work

- I have done everything you said in the readme
- the action runs without error in my repo
- but then nothing more happens, no new file or folder .traffic is visible in my repo...

where is the data now?

**Comment by sangonzal** [comment]
Hi @theworldisnotflat, it depends on what kind of work flow you create in your .yml file. For example if you follow the simplest option of committing to your repository, like [this one](https://github.com/sangonzal/repository-traffic-action#sample-workflow-that-runs-weekly-and-commits-files-to-repository), they'll be in a branch named `traffic` in your repository. There you should see a folder traffic which contains the data. 

You can of course upload the data to wherever you like by inserting another action into your workflow - for example to upload to Azure storage or Amazon S3.

**Comment by theworldisnotflat** [comment]
ah! now I see that my task has not run yet, what ran is only the creation of the file 'create save_stats.yml'... I will wait until tomorrow 'sunday' , the day of the job to see whether this new branch appears!

**Comment by theworldisnotflat** [comment]
Here is the code, below.
It failed on run yesterday with Error: The process '/usr/bin/git' failed with exit code 1

from the logs:
```
   /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/traffic*:refs/remotes/origin/traffic* +refs/tags/traffic*:refs/tags/traffic*
  The process '/usr/bin/git' failed with exit code 1
  Waiting 10 seconds before trying again
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/traffic*:refs/remotes/origin/traffic* +refs/tags/traffic*:refs/tags/traffic*
  The process '/usr/bin/git' failed with exit code 1
  Waiting 17 seconds before trying again
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/traffic*:refs/remotes/origin/traffic* +refs/tags/traffic*:refs/tags/traffic*
```
The source code for my action, based on your example:
```
on:
  schedule: 
    # runs once a week on sunday
    - cron: "55 23 * * 0"
    
jobs:
  # This workflow contains a single job called "traffic"
  traffic:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        ref: "traffic"
    
    # Calculates traffic and clones and stores in CSV file
    - name: GitHub traffic 
      uses: sangonzal/repository-traffic-action@v0.1.4
      env:
        TRAFFIC_ACTION_TOKEN: ${{ secrets.TRAFFIC_ACTION_TOKEN }} 
     
    # Commits files to repository
    - name: Commit changes
      uses: EndBug/add-and-commit@v4
      with:
        author_name: Santiago Gonzalez
        message: "GitHub traffic"
        add: "./traffic/*"
        ref: "traffic"  # commits to branch "traffic" 
```
