### ISSUE TITLE
Action will fail in forks

### ISSUE THREAD

**Issue by thias15** [sangonzal/repository-traffic-action#19]
Thanks for this very handy action. The problem I encountered is that the action will fail for anyone forking the repo since it relies on a PAT. Any ideas for a workaround?

**Comment by sangonzal** [comment]
Hi @thias15! Should a forked repositories views and clones count towards the upstream repository? Do you know what GitHub does for this scenario? 

I think I would expect a forked repos stats to be separate from the upstream repo, given that forked repo can become it's own separate thing. 

Either way I don't think there is anything that can be done, apart from the person who forked creating a PAT and using it to log metrics for the fork.

**Comment by thias15** [comment]
It would be nice to have the repo name as an input rather than using `GITHUB_REPOSITORY`

**Comment by sangonzal** [comment]
Sorry, hadn't seen your latest comment. I think it would be reasonable to let the user override GITHUB_REPOSITORY with their own value by setting an env variable. By the way have you tried overriding GITHUB_REPOSITORY by setting it on the yaml file? Something along the lines of: 

```
    - name: GitHub traffic 
      uses: sangonzal/repository-traffic-action@v0.1.4
      env:
        TRAFFIC_ACTION_TOKEN: ${{ secrets.TRAFFIC_ACTION_TOKEN }}
         GITHUB_REPOSITORY: name_you_want_to_use
```

I don't have time to make the changes and test right now, but if you'd like to make the change I would merge the pull request in and release a new version.
